package tracker;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class IdConflictTest {
    @Test
    void shouldNotConflictBetweenManuallySetIdAndAutoGeneratedId() {
        HistoryManager dummyHistoryManager = new HistoryManager() {
            @Override
            public void add(Task task) {}
            @Override
            public List<Task> getHistory() {
                return new ArrayList<>();
            }
        };

        InMemoryTaskManager taskManager = new InMemoryTaskManager(dummyHistoryManager);

        // Вручную задаём ID
        Task manualTask = new Task("Manual Task", "Created manually", TaskStatus.NEW);
        manualTask.setId(42); // вручную выбранный ID
        taskManager.addNewTask(manualTask); // добавляем через метод менеджера

        // Добавляем через менеджер, который использует nextId
        Task generatedTask = new Task("Generated Task", "Created by manager", TaskStatus.NEW);
        int generatedId = taskManager.addNewTask(generatedTask);

        // Проверяем, что ID не пересекаются
        assertNotEquals(manualTask.getId(), generatedId, "Generated ID конфликтует с вручную заданным");
    }
}
